#!/bin/bash

export PATH=`dirname $0`:${PATH}
export LC_ALL=C

. .settings || exit 99
SECRETSHA1=`echo -n ${SECRET} | sha1sum - | cut -c1-40`

id=${1:-0}

# do not use -i as json_pp will choke on it
echo "Selected treatment record:"
curl \
    -H "API-SECRET: ${SECRETSHA1}" \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    "https://${SERVER}:${PORT}/api/v1/treatments.json?x=1&count=10&find\[_id\]=${id}" \
| json_pp
echo ""

read -p "proceed? " x
curl \
    -X DELETE \
    -H "API-SECRET: ${SECRETSHA1}" \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    "https://${SERVER}:${PORT}/api/v1/treatments.json?x=2&count=10&find\[_id\]=${id}"
echo ""

#read -p "proceed? " x
echo "Check for treatment record:"
curl \
    -H "API-SECRET: ${SECRETSHA1}" \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    "https://${SERVER}:${PORT}/api/v1/treatments.json?x=3&count=10&find\[_id\]=${id}"
echo ""
