#!/bin/bash

#SECRET="MyAPIsecret"
#SERVER="MyNSinstance"
#PORT=4711
. .settings
SECRETSHA1=`echo -n ${SECRET} | sha1sum - | cut -c1-40`

mkdir -p data
echo querying last sgv ...
LANG=C \
curl \
    -s \
    -H "API-SECRET: ${SECRETSHA1}" \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    "https://${SERVER}:${PORT}/api/v1/entries.json?count=1&find\[dateString\]\[\$gte\]=2020-01-01&find\[type\]=sgv" \
| tee /dev/stderr \
| sed -e 's~.*"date":\([0-9]*\)[^0-9].*~\1~' -e 's~null~0~' \
> data/last-sgv.time
echo ""
# FIXME: handle empty result

exit
