#!/bin/bash

#SECRET="MyAPIsecret"
#SERVER="MyNSinstance"
#PORT=4711
. .settings
SECRETSHA1=`echo -n ${SECRET} | sha1sum - | cut -c1-40`

mkdir -p data
echo querying last sensor ...
LANG=C \
curl \
    -s \
    -H "API-SECRET: ${SECRETSHA1}" \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    "https://${SERVER}:${PORT}/api/v1/treatments.json?count=1&x=`date +%s`&find\[created_at\]\[\$gte\]=2020-01-01&find\[eventType\]=/Sensor/" \
| tee /dev/stderr \
| sed -e 's~.*"date":\([0-9]*\)[^0-9].*~\1~' -e 's~null~0~' \
> data/last-sensor.time
echo ""
# FIXME: handle empty result

exit
